CREATE TABLE IF NOT EXISTS drugs
(
    guid CHAR(36) PRIMARY KEY NOT NULL,
    name VARCHAR(255) NOT NULL,
    count BIGINT NOT NULL,
);

ALTER TABLE drugs
    ADD CONSTRAINT drugs_guid_foreign FOREIGN KEY(guid) REFERENCES animal_type (guid) ON DELETE CASCADE;

